/*
 * Forem API V1
 * Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BillboardsGetByIdResponse
 */
public class BillboardsGetByIdResponseTest {
    private final BillboardsGetByIdResponse model = new BillboardsGetByIdResponse();

    /**
     * Model tests for BillboardsGetByIdResponse
     */
    @Test
    public void testBillboardsGetByIdResponse() {
        // TODO: test BillboardsGetByIdResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'approved'
     */
    @Test
    public void approvedTest() {
        // TODO: test approved
    }

    /**
     * Test the property 'audienceSegmentId'
     */
    @Test
    public void audienceSegmentIdTest() {
        // TODO: test audienceSegmentId
    }

    /**
     * Test the property 'bodyMarkdown'
     */
    @Test
    public void bodyMarkdownTest() {
        // TODO: test bodyMarkdown
    }

    /**
     * Test the property 'cachedTagList'
     */
    @Test
    public void cachedTagListTest() {
        // TODO: test cachedTagList
    }

    /**
     * Test the property 'clicksCount'
     */
    @Test
    public void clicksCountTest() {
        // TODO: test clicksCount
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'creatorId'
     */
    @Test
    public void creatorIdTest() {
        // TODO: test creatorId
    }

    /**
     * Test the property 'customDisplayLabel'
     */
    @Test
    public void customDisplayLabelTest() {
        // TODO: test customDisplayLabel
    }

    /**
     * Test the property 'displayTo'
     */
    @Test
    public void displayToTest() {
        // TODO: test displayTo
    }

    /**
     * Test the property 'excludeArticleIds'
     */
    @Test
    public void excludeArticleIdsTest() {
        // TODO: test excludeArticleIds
    }

    /**
     * Test the property 'impressionsCount'
     */
    @Test
    public void impressionsCountTest() {
        // TODO: test impressionsCount
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'organizationId'
     */
    @Test
    public void organizationIdTest() {
        // TODO: test organizationId
    }

    /**
     * Test the property 'placementArea'
     */
    @Test
    public void placementAreaTest() {
        // TODO: test placementArea
    }

    /**
     * Test the property 'priority'
     */
    @Test
    public void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'processedHtml'
     */
    @Test
    public void processedHtmlTest() {
        // TODO: test processedHtml
    }

    /**
     * Test the property 'published'
     */
    @Test
    public void publishedTest() {
        // TODO: test published
    }

    /**
     * Test the property 'renderMode'
     */
    @Test
    public void renderModeTest() {
        // TODO: test renderMode
    }

    /**
     * Test the property 'successRate'
     */
    @Test
    public void successRateTest() {
        // TODO: test successRate
    }

    /**
     * Test the property 'template'
     */
    @Test
    public void templateTest() {
        // TODO: test template
    }

    /**
     * Test the property 'typeOf'
     */
    @Test
    public void typeOfTest() {
        // TODO: test typeOf
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'weight'
     */
    @Test
    public void weightTest() {
        // TODO: test weight
    }

    /**
     * Test the property 'audienceSegmentType'
     */
    @Test
    public void audienceSegmentTypeTest() {
        // TODO: test audienceSegmentType
    }

    /**
     * Test the property 'tagList'
     */
    @Test
    public void tagListTest() {
        // TODO: test tagList
    }

    /**
     * Test the property 'targetGeolocations'
     */
    @Test
    public void targetGeolocationsTest() {
        // TODO: test targetGeolocations
    }

}
