/*
 * Forem API V1
 * Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Organization
 */
public class OrganizationTest {
    private final Organization model = new Organization();

    /**
     * Model tests for Organization
     */
    @Test
    public void testOrganization() {
        // TODO: test Organization
    }

    /**
     * Test the property 'summary'
     */
    @Test
    public void summaryTest() {
        // TODO: test summary
    }

    /**
     * Test the property 'typeOf'
     */
    @Test
    public void typeOfTest() {
        // TODO: test typeOf
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'twitterUsername'
     */
    @Test
    public void twitterUsernameTest() {
        // TODO: test twitterUsername
    }

    /**
     * Test the property 'githubUsername'
     */
    @Test
    public void githubUsernameTest() {
        // TODO: test githubUsername
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'joinedAt'
     */
    @Test
    public void joinedAtTest() {
        // TODO: test joinedAt
    }

    /**
     * Test the property 'techStack'
     */
    @Test
    public void techStackTest() {
        // TODO: test techStack
    }

    /**
     * Test the property 'tagLine'
     */
    @Test
    public void tagLineTest() {
        // TODO: test tagLine
    }

    /**
     * Test the property 'story'
     */
    @Test
    public void storyTest() {
        // TODO: test story
    }

}
