/*
 * Forem API V1
 * Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Flare tag of the article
 */
@ApiModel(description = "Flare tag of the article")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ArticleFlareTag {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_BG_COLOR_HEX = "bg_color_hex";
  @SerializedName(SERIALIZED_NAME_BG_COLOR_HEX)
  private String bgColorHex;

  public static final String SERIALIZED_NAME_TEXT_COLOR_HEX = "text_color_hex";
  @SerializedName(SERIALIZED_NAME_TEXT_COLOR_HEX)
  private String textColorHex;

  public ArticleFlareTag() {
  }

  public ArticleFlareTag name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public ArticleFlareTag bgColorHex(String bgColorHex) {
    
    
    
    
    this.bgColorHex = bgColorHex;
    return this;
  }

   /**
   * Background color (hexadecimal)
   * @return bgColorHex
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Background color (hexadecimal)")

  public String getBgColorHex() {
    return bgColorHex;
  }


  public void setBgColorHex(String bgColorHex) {
    
    
    
    this.bgColorHex = bgColorHex;
  }


  public ArticleFlareTag textColorHex(String textColorHex) {
    
    
    
    
    this.textColorHex = textColorHex;
    return this;
  }

   /**
   * Text color (hexadecimal)
   * @return textColorHex
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Text color (hexadecimal)")

  public String getTextColorHex() {
    return textColorHex;
  }


  public void setTextColorHex(String textColorHex) {
    
    
    
    this.textColorHex = textColorHex;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ArticleFlareTag instance itself
   */
  public ArticleFlareTag putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArticleFlareTag articleFlareTag = (ArticleFlareTag) o;
    return Objects.equals(this.name, articleFlareTag.name) &&
        Objects.equals(this.bgColorHex, articleFlareTag.bgColorHex) &&
        Objects.equals(this.textColorHex, articleFlareTag.textColorHex)&&
        Objects.equals(this.additionalProperties, articleFlareTag.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, bgColorHex, textColorHex, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArticleFlareTag {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    bgColorHex: ").append(toIndentedString(bgColorHex)).append("\n");
    sb.append("    textColorHex: ").append(toIndentedString(textColorHex)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("bg_color_hex");
    openapiFields.add("text_color_hex");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ArticleFlareTag
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ArticleFlareTag.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ArticleFlareTag is not found in the empty JSON string", ArticleFlareTag.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("bg_color_hex").isJsonNull() && (jsonObj.get("bg_color_hex") != null && !jsonObj.get("bg_color_hex").isJsonNull()) && !jsonObj.get("bg_color_hex").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `bg_color_hex` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bg_color_hex").toString()));
      }
      if (!jsonObj.get("text_color_hex").isJsonNull() && (jsonObj.get("text_color_hex") != null && !jsonObj.get("text_color_hex").isJsonNull()) && !jsonObj.get("text_color_hex").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `text_color_hex` to be a primitive type in the JSON string but got `%s`", jsonObj.get("text_color_hex").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ArticleFlareTag.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ArticleFlareTag' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ArticleFlareTag> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ArticleFlareTag.class));

       return (TypeAdapter<T>) new TypeAdapter<ArticleFlareTag>() {
           @Override
           public void write(JsonWriter out, ArticleFlareTag value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ArticleFlareTag read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ArticleFlareTag instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ArticleFlareTag given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ArticleFlareTag
  * @throws IOException if the JSON string is invalid with respect to ArticleFlareTag
  */
  public static ArticleFlareTag fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ArticleFlareTag.class);
  }

 /**
  * Convert an instance of ArticleFlareTag to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

