/*
 * Forem API V1
 * Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * BillboardsGetByIdResponse
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class BillboardsGetByIdResponse {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Double id;

  public static final String SERIALIZED_NAME_APPROVED = "approved";
  @SerializedName(SERIALIZED_NAME_APPROVED)
  private Boolean approved;

  public static final String SERIALIZED_NAME_AUDIENCE_SEGMENT_ID = "audience_segment_id";
  @SerializedName(SERIALIZED_NAME_AUDIENCE_SEGMENT_ID)
  private String audienceSegmentId;

  public static final String SERIALIZED_NAME_BODY_MARKDOWN = "body_markdown";
  @SerializedName(SERIALIZED_NAME_BODY_MARKDOWN)
  private String bodyMarkdown;

  public static final String SERIALIZED_NAME_CACHED_TAG_LIST = "cached_tag_list";
  @SerializedName(SERIALIZED_NAME_CACHED_TAG_LIST)
  private String cachedTagList;

  public static final String SERIALIZED_NAME_CLICKS_COUNT = "clicks_count";
  @SerializedName(SERIALIZED_NAME_CLICKS_COUNT)
  private Double clicksCount;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_CREATOR_ID = "creator_id";
  @SerializedName(SERIALIZED_NAME_CREATOR_ID)
  private String creatorId;

  public static final String SERIALIZED_NAME_CUSTOM_DISPLAY_LABEL = "custom_display_label";
  @SerializedName(SERIALIZED_NAME_CUSTOM_DISPLAY_LABEL)
  private String customDisplayLabel;

  public static final String SERIALIZED_NAME_DISPLAY_TO = "display_to";
  @SerializedName(SERIALIZED_NAME_DISPLAY_TO)
  private String displayTo;

  public static final String SERIALIZED_NAME_EXCLUDE_ARTICLE_IDS = "exclude_article_ids";
  @SerializedName(SERIALIZED_NAME_EXCLUDE_ARTICLE_IDS)
  private String excludeArticleIds;

  public static final String SERIALIZED_NAME_IMPRESSIONS_COUNT = "impressions_count";
  @SerializedName(SERIALIZED_NAME_IMPRESSIONS_COUNT)
  private Double impressionsCount;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_ORGANIZATION_ID = "organization_id";
  @SerializedName(SERIALIZED_NAME_ORGANIZATION_ID)
  private Double organizationId;

  public static final String SERIALIZED_NAME_PLACEMENT_AREA = "placement_area";
  @SerializedName(SERIALIZED_NAME_PLACEMENT_AREA)
  private String placementArea;

  public static final String SERIALIZED_NAME_PRIORITY = "priority";
  @SerializedName(SERIALIZED_NAME_PRIORITY)
  private Boolean priority;

  public static final String SERIALIZED_NAME_PROCESSED_HTML = "processed_html";
  @SerializedName(SERIALIZED_NAME_PROCESSED_HTML)
  private String processedHtml;

  public static final String SERIALIZED_NAME_PUBLISHED = "published";
  @SerializedName(SERIALIZED_NAME_PUBLISHED)
  private Boolean published;

  public static final String SERIALIZED_NAME_RENDER_MODE = "render_mode";
  @SerializedName(SERIALIZED_NAME_RENDER_MODE)
  private String renderMode;

  public static final String SERIALIZED_NAME_SUCCESS_RATE = "success_rate";
  @SerializedName(SERIALIZED_NAME_SUCCESS_RATE)
  private Double successRate;

  public static final String SERIALIZED_NAME_TEMPLATE = "template";
  @SerializedName(SERIALIZED_NAME_TEMPLATE)
  private String template;

  public static final String SERIALIZED_NAME_TYPE_OF = "type_of";
  @SerializedName(SERIALIZED_NAME_TYPE_OF)
  private String typeOf;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;

  public static final String SERIALIZED_NAME_WEIGHT = "weight";
  @SerializedName(SERIALIZED_NAME_WEIGHT)
  private Double weight;

  public static final String SERIALIZED_NAME_AUDIENCE_SEGMENT_TYPE = "audience_segment_type";
  @SerializedName(SERIALIZED_NAME_AUDIENCE_SEGMENT_TYPE)
  private String audienceSegmentType;

  public static final String SERIALIZED_NAME_TAG_LIST = "tag_list";
  @SerializedName(SERIALIZED_NAME_TAG_LIST)
  private String tagList;

  public static final String SERIALIZED_NAME_TARGET_GEOLOCATIONS = "target_geolocations";
  @SerializedName(SERIALIZED_NAME_TARGET_GEOLOCATIONS)
  private List<String> targetGeolocations = null;

  public BillboardsGetByIdResponse() {
  }

  public BillboardsGetByIdResponse id(Double id) {
    
    
    
    
    this.id = id;
    return this;
  }

  public BillboardsGetByIdResponse id(Integer id) {
    
    
    
    
    this.id = id.doubleValue();
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "3", value = "")

  public Double getId() {
    return id;
  }


  public void setId(Double id) {
    
    
    
    this.id = id;
  }


  public BillboardsGetByIdResponse approved(Boolean approved) {
    
    
    
    
    this.approved = approved;
    return this;
  }

   /**
   * Get approved
   * @return approved
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "")

  public Boolean getApproved() {
    return approved;
  }


  public void setApproved(Boolean approved) {
    
    
    
    this.approved = approved;
  }


  public BillboardsGetByIdResponse audienceSegmentId(String audienceSegmentId) {
    
    
    
    
    this.audienceSegmentId = audienceSegmentId;
    return this;
  }

   /**
   * Get audienceSegmentId
   * @return audienceSegmentId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAudienceSegmentId() {
    return audienceSegmentId;
  }


  public void setAudienceSegmentId(String audienceSegmentId) {
    
    
    
    this.audienceSegmentId = audienceSegmentId;
  }


  public BillboardsGetByIdResponse bodyMarkdown(String bodyMarkdown) {
    
    
    
    
    this.bodyMarkdown = bodyMarkdown;
    return this;
  }

   /**
   * Get bodyMarkdown
   * @return bodyMarkdown
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Hello _hey_ Hey hey 2", value = "")

  public String getBodyMarkdown() {
    return bodyMarkdown;
  }


  public void setBodyMarkdown(String bodyMarkdown) {
    
    
    
    this.bodyMarkdown = bodyMarkdown;
  }


  public BillboardsGetByIdResponse cachedTagList(String cachedTagList) {
    
    
    
    
    this.cachedTagList = cachedTagList;
    return this;
  }

   /**
   * Get cachedTagList
   * @return cachedTagList
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "", value = "")

  public String getCachedTagList() {
    return cachedTagList;
  }


  public void setCachedTagList(String cachedTagList) {
    
    
    
    this.cachedTagList = cachedTagList;
  }


  public BillboardsGetByIdResponse clicksCount(Double clicksCount) {
    
    
    
    
    this.clicksCount = clicksCount;
    return this;
  }

  public BillboardsGetByIdResponse clicksCount(Integer clicksCount) {
    
    
    
    
    this.clicksCount = clicksCount.doubleValue();
    return this;
  }

   /**
   * Get clicksCount
   * @return clicksCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "")

  public Double getClicksCount() {
    return clicksCount;
  }


  public void setClicksCount(Double clicksCount) {
    
    
    
    this.clicksCount = clicksCount;
  }


  public BillboardsGetByIdResponse createdAt(String createdAt) {
    
    
    
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2023-12-15T11:15:34.492+11:00", value = "")

  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    
    
    
    this.createdAt = createdAt;
  }


  public BillboardsGetByIdResponse creatorId(String creatorId) {
    
    
    
    
    this.creatorId = creatorId;
    return this;
  }

   /**
   * Get creatorId
   * @return creatorId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCreatorId() {
    return creatorId;
  }


  public void setCreatorId(String creatorId) {
    
    
    
    this.creatorId = creatorId;
  }


  public BillboardsGetByIdResponse customDisplayLabel(String customDisplayLabel) {
    
    
    
    
    this.customDisplayLabel = customDisplayLabel;
    return this;
  }

   /**
   * Get customDisplayLabel
   * @return customDisplayLabel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCustomDisplayLabel() {
    return customDisplayLabel;
  }


  public void setCustomDisplayLabel(String customDisplayLabel) {
    
    
    
    this.customDisplayLabel = customDisplayLabel;
  }


  public BillboardsGetByIdResponse displayTo(String displayTo) {
    
    
    
    
    this.displayTo = displayTo;
    return this;
  }

   /**
   * Get displayTo
   * @return displayTo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "all", value = "")

  public String getDisplayTo() {
    return displayTo;
  }


  public void setDisplayTo(String displayTo) {
    
    
    
    this.displayTo = displayTo;
  }


  public BillboardsGetByIdResponse excludeArticleIds(String excludeArticleIds) {
    
    
    
    
    this.excludeArticleIds = excludeArticleIds;
    return this;
  }

   /**
   * Get excludeArticleIds
   * @return excludeArticleIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "", value = "")

  public String getExcludeArticleIds() {
    return excludeArticleIds;
  }


  public void setExcludeArticleIds(String excludeArticleIds) {
    
    
    
    this.excludeArticleIds = excludeArticleIds;
  }


  public BillboardsGetByIdResponse impressionsCount(Double impressionsCount) {
    
    
    
    
    this.impressionsCount = impressionsCount;
    return this;
  }

  public BillboardsGetByIdResponse impressionsCount(Integer impressionsCount) {
    
    
    
    
    this.impressionsCount = impressionsCount.doubleValue();
    return this;
  }

   /**
   * Get impressionsCount
   * @return impressionsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "")

  public Double getImpressionsCount() {
    return impressionsCount;
  }


  public void setImpressionsCount(Double impressionsCount) {
    
    
    
    this.impressionsCount = impressionsCount;
  }


  public BillboardsGetByIdResponse name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Billboard 3", value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public BillboardsGetByIdResponse organizationId(Double organizationId) {
    
    
    
    
    this.organizationId = organizationId;
    return this;
  }

  public BillboardsGetByIdResponse organizationId(Integer organizationId) {
    
    
    
    
    this.organizationId = organizationId.doubleValue();
    return this;
  }

   /**
   * Get organizationId
   * @return organizationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "6", value = "")

  public Double getOrganizationId() {
    return organizationId;
  }


  public void setOrganizationId(Double organizationId) {
    
    
    
    this.organizationId = organizationId;
  }


  public BillboardsGetByIdResponse placementArea(String placementArea) {
    
    
    
    
    this.placementArea = placementArea;
    return this;
  }

   /**
   * Get placementArea
   * @return placementArea
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "sidebar_left", value = "")

  public String getPlacementArea() {
    return placementArea;
  }


  public void setPlacementArea(String placementArea) {
    
    
    
    this.placementArea = placementArea;
  }


  public BillboardsGetByIdResponse priority(Boolean priority) {
    
    
    
    
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "")

  public Boolean getPriority() {
    return priority;
  }


  public void setPriority(Boolean priority) {
    
    
    
    this.priority = priority;
  }


  public BillboardsGetByIdResponse processedHtml(String processedHtml) {
    
    
    
    
    this.processedHtml = processedHtml;
    return this;
  }

   /**
   * Get processedHtml
   * @return processedHtml
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "<p>Hello <em>hey</em> Hey hey 2</p>", value = "")

  public String getProcessedHtml() {
    return processedHtml;
  }


  public void setProcessedHtml(String processedHtml) {
    
    
    
    this.processedHtml = processedHtml;
  }


  public BillboardsGetByIdResponse published(Boolean published) {
    
    
    
    
    this.published = published;
    return this;
  }

   /**
   * Get published
   * @return published
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "")

  public Boolean getPublished() {
    return published;
  }


  public void setPublished(Boolean published) {
    
    
    
    this.published = published;
  }


  public BillboardsGetByIdResponse renderMode(String renderMode) {
    
    
    
    
    this.renderMode = renderMode;
    return this;
  }

   /**
   * Get renderMode
   * @return renderMode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "forem_markdown", value = "")

  public String getRenderMode() {
    return renderMode;
  }


  public void setRenderMode(String renderMode) {
    
    
    
    this.renderMode = renderMode;
  }


  public BillboardsGetByIdResponse successRate(Double successRate) {
    
    
    
    
    this.successRate = successRate;
    return this;
  }

  public BillboardsGetByIdResponse successRate(Integer successRate) {
    
    
    
    
    this.successRate = successRate.doubleValue();
    return this;
  }

   /**
   * Get successRate
   * @return successRate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "")

  public Double getSuccessRate() {
    return successRate;
  }


  public void setSuccessRate(Double successRate) {
    
    
    
    this.successRate = successRate;
  }


  public BillboardsGetByIdResponse template(String template) {
    
    
    
    
    this.template = template;
    return this;
  }

   /**
   * Get template
   * @return template
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "authorship_box", value = "")

  public String getTemplate() {
    return template;
  }


  public void setTemplate(String template) {
    
    
    
    this.template = template;
  }


  public BillboardsGetByIdResponse typeOf(String typeOf) {
    
    
    
    
    this.typeOf = typeOf;
    return this;
  }

   /**
   * Get typeOf
   * @return typeOf
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "in_house", value = "")

  public String getTypeOf() {
    return typeOf;
  }


  public void setTypeOf(String typeOf) {
    
    
    
    this.typeOf = typeOf;
  }


  public BillboardsGetByIdResponse updatedAt(String updatedAt) {
    
    
    
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2023-12-15T11:15:34.495+11:00", value = "")

  public String getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(String updatedAt) {
    
    
    
    this.updatedAt = updatedAt;
  }


  public BillboardsGetByIdResponse weight(Double weight) {
    
    
    
    
    this.weight = weight;
    return this;
  }

  public BillboardsGetByIdResponse weight(Integer weight) {
    
    
    
    
    this.weight = weight.doubleValue();
    return this;
  }

   /**
   * Get weight
   * @return weight
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "")

  public Double getWeight() {
    return weight;
  }


  public void setWeight(Double weight) {
    
    
    
    this.weight = weight;
  }


  public BillboardsGetByIdResponse audienceSegmentType(String audienceSegmentType) {
    
    
    
    
    this.audienceSegmentType = audienceSegmentType;
    return this;
  }

   /**
   * Get audienceSegmentType
   * @return audienceSegmentType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAudienceSegmentType() {
    return audienceSegmentType;
  }


  public void setAudienceSegmentType(String audienceSegmentType) {
    
    
    
    this.audienceSegmentType = audienceSegmentType;
  }


  public BillboardsGetByIdResponse tagList(String tagList) {
    
    
    
    
    this.tagList = tagList;
    return this;
  }

   /**
   * Get tagList
   * @return tagList
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "", value = "")

  public String getTagList() {
    return tagList;
  }


  public void setTagList(String tagList) {
    
    
    
    this.tagList = tagList;
  }


  public BillboardsGetByIdResponse targetGeolocations(List<String> targetGeolocations) {
    
    
    
    
    this.targetGeolocations = targetGeolocations;
    return this;
  }

  public BillboardsGetByIdResponse addTargetGeolocationsItem(String targetGeolocationsItem) {
    if (this.targetGeolocations == null) {
      this.targetGeolocations = new ArrayList<>();
    }
    this.targetGeolocations.add(targetGeolocationsItem);
    return this;
  }

   /**
   * Get targetGeolocations
   * @return targetGeolocations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getTargetGeolocations() {
    return targetGeolocations;
  }


  public void setTargetGeolocations(List<String> targetGeolocations) {
    
    
    
    this.targetGeolocations = targetGeolocations;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the BillboardsGetByIdResponse instance itself
   */
  public BillboardsGetByIdResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BillboardsGetByIdResponse billboardsGetByIdResponse = (BillboardsGetByIdResponse) o;
    return Objects.equals(this.id, billboardsGetByIdResponse.id) &&
        Objects.equals(this.approved, billboardsGetByIdResponse.approved) &&
        Objects.equals(this.audienceSegmentId, billboardsGetByIdResponse.audienceSegmentId) &&
        Objects.equals(this.bodyMarkdown, billboardsGetByIdResponse.bodyMarkdown) &&
        Objects.equals(this.cachedTagList, billboardsGetByIdResponse.cachedTagList) &&
        Objects.equals(this.clicksCount, billboardsGetByIdResponse.clicksCount) &&
        Objects.equals(this.createdAt, billboardsGetByIdResponse.createdAt) &&
        Objects.equals(this.creatorId, billboardsGetByIdResponse.creatorId) &&
        Objects.equals(this.customDisplayLabel, billboardsGetByIdResponse.customDisplayLabel) &&
        Objects.equals(this.displayTo, billboardsGetByIdResponse.displayTo) &&
        Objects.equals(this.excludeArticleIds, billboardsGetByIdResponse.excludeArticleIds) &&
        Objects.equals(this.impressionsCount, billboardsGetByIdResponse.impressionsCount) &&
        Objects.equals(this.name, billboardsGetByIdResponse.name) &&
        Objects.equals(this.organizationId, billboardsGetByIdResponse.organizationId) &&
        Objects.equals(this.placementArea, billboardsGetByIdResponse.placementArea) &&
        Objects.equals(this.priority, billboardsGetByIdResponse.priority) &&
        Objects.equals(this.processedHtml, billboardsGetByIdResponse.processedHtml) &&
        Objects.equals(this.published, billboardsGetByIdResponse.published) &&
        Objects.equals(this.renderMode, billboardsGetByIdResponse.renderMode) &&
        Objects.equals(this.successRate, billboardsGetByIdResponse.successRate) &&
        Objects.equals(this.template, billboardsGetByIdResponse.template) &&
        Objects.equals(this.typeOf, billboardsGetByIdResponse.typeOf) &&
        Objects.equals(this.updatedAt, billboardsGetByIdResponse.updatedAt) &&
        Objects.equals(this.weight, billboardsGetByIdResponse.weight) &&
        Objects.equals(this.audienceSegmentType, billboardsGetByIdResponse.audienceSegmentType) &&
        Objects.equals(this.tagList, billboardsGetByIdResponse.tagList) &&
        Objects.equals(this.targetGeolocations, billboardsGetByIdResponse.targetGeolocations)&&
        Objects.equals(this.additionalProperties, billboardsGetByIdResponse.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, approved, audienceSegmentId, bodyMarkdown, cachedTagList, clicksCount, createdAt, creatorId, customDisplayLabel, displayTo, excludeArticleIds, impressionsCount, name, organizationId, placementArea, priority, processedHtml, published, renderMode, successRate, template, typeOf, updatedAt, weight, audienceSegmentType, tagList, targetGeolocations, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillboardsGetByIdResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    approved: ").append(toIndentedString(approved)).append("\n");
    sb.append("    audienceSegmentId: ").append(toIndentedString(audienceSegmentId)).append("\n");
    sb.append("    bodyMarkdown: ").append(toIndentedString(bodyMarkdown)).append("\n");
    sb.append("    cachedTagList: ").append(toIndentedString(cachedTagList)).append("\n");
    sb.append("    clicksCount: ").append(toIndentedString(clicksCount)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    creatorId: ").append(toIndentedString(creatorId)).append("\n");
    sb.append("    customDisplayLabel: ").append(toIndentedString(customDisplayLabel)).append("\n");
    sb.append("    displayTo: ").append(toIndentedString(displayTo)).append("\n");
    sb.append("    excludeArticleIds: ").append(toIndentedString(excludeArticleIds)).append("\n");
    sb.append("    impressionsCount: ").append(toIndentedString(impressionsCount)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    placementArea: ").append(toIndentedString(placementArea)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    processedHtml: ").append(toIndentedString(processedHtml)).append("\n");
    sb.append("    published: ").append(toIndentedString(published)).append("\n");
    sb.append("    renderMode: ").append(toIndentedString(renderMode)).append("\n");
    sb.append("    successRate: ").append(toIndentedString(successRate)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    typeOf: ").append(toIndentedString(typeOf)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    audienceSegmentType: ").append(toIndentedString(audienceSegmentType)).append("\n");
    sb.append("    tagList: ").append(toIndentedString(tagList)).append("\n");
    sb.append("    targetGeolocations: ").append(toIndentedString(targetGeolocations)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("approved");
    openapiFields.add("audience_segment_id");
    openapiFields.add("body_markdown");
    openapiFields.add("cached_tag_list");
    openapiFields.add("clicks_count");
    openapiFields.add("created_at");
    openapiFields.add("creator_id");
    openapiFields.add("custom_display_label");
    openapiFields.add("display_to");
    openapiFields.add("exclude_article_ids");
    openapiFields.add("impressions_count");
    openapiFields.add("name");
    openapiFields.add("organization_id");
    openapiFields.add("placement_area");
    openapiFields.add("priority");
    openapiFields.add("processed_html");
    openapiFields.add("published");
    openapiFields.add("render_mode");
    openapiFields.add("success_rate");
    openapiFields.add("template");
    openapiFields.add("type_of");
    openapiFields.add("updated_at");
    openapiFields.add("weight");
    openapiFields.add("audience_segment_type");
    openapiFields.add("tag_list");
    openapiFields.add("target_geolocations");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to BillboardsGetByIdResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!BillboardsGetByIdResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BillboardsGetByIdResponse is not found in the empty JSON string", BillboardsGetByIdResponse.openapiRequiredFields.toString()));
        }
      }
      if (!jsonObj.get("audience_segment_id").isJsonNull() && (jsonObj.get("audience_segment_id") != null && !jsonObj.get("audience_segment_id").isJsonNull()) && !jsonObj.get("audience_segment_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `audience_segment_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("audience_segment_id").toString()));
      }
      if ((jsonObj.get("body_markdown") != null && !jsonObj.get("body_markdown").isJsonNull()) && !jsonObj.get("body_markdown").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `body_markdown` to be a primitive type in the JSON string but got `%s`", jsonObj.get("body_markdown").toString()));
      }
      if ((jsonObj.get("cached_tag_list") != null && !jsonObj.get("cached_tag_list").isJsonNull()) && !jsonObj.get("cached_tag_list").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cached_tag_list` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cached_tag_list").toString()));
      }
      if ((jsonObj.get("created_at") != null && !jsonObj.get("created_at").isJsonNull()) && !jsonObj.get("created_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `created_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("created_at").toString()));
      }
      if (!jsonObj.get("creator_id").isJsonNull() && (jsonObj.get("creator_id") != null && !jsonObj.get("creator_id").isJsonNull()) && !jsonObj.get("creator_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `creator_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("creator_id").toString()));
      }
      if (!jsonObj.get("custom_display_label").isJsonNull() && (jsonObj.get("custom_display_label") != null && !jsonObj.get("custom_display_label").isJsonNull()) && !jsonObj.get("custom_display_label").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `custom_display_label` to be a primitive type in the JSON string but got `%s`", jsonObj.get("custom_display_label").toString()));
      }
      if ((jsonObj.get("display_to") != null && !jsonObj.get("display_to").isJsonNull()) && !jsonObj.get("display_to").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `display_to` to be a primitive type in the JSON string but got `%s`", jsonObj.get("display_to").toString()));
      }
      if ((jsonObj.get("exclude_article_ids") != null && !jsonObj.get("exclude_article_ids").isJsonNull()) && !jsonObj.get("exclude_article_ids").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `exclude_article_ids` to be a primitive type in the JSON string but got `%s`", jsonObj.get("exclude_article_ids").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("placement_area") != null && !jsonObj.get("placement_area").isJsonNull()) && !jsonObj.get("placement_area").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `placement_area` to be a primitive type in the JSON string but got `%s`", jsonObj.get("placement_area").toString()));
      }
      if ((jsonObj.get("processed_html") != null && !jsonObj.get("processed_html").isJsonNull()) && !jsonObj.get("processed_html").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `processed_html` to be a primitive type in the JSON string but got `%s`", jsonObj.get("processed_html").toString()));
      }
      if ((jsonObj.get("render_mode") != null && !jsonObj.get("render_mode").isJsonNull()) && !jsonObj.get("render_mode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `render_mode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("render_mode").toString()));
      }
      if ((jsonObj.get("template") != null && !jsonObj.get("template").isJsonNull()) && !jsonObj.get("template").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `template` to be a primitive type in the JSON string but got `%s`", jsonObj.get("template").toString()));
      }
      if ((jsonObj.get("type_of") != null && !jsonObj.get("type_of").isJsonNull()) && !jsonObj.get("type_of").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type_of` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type_of").toString()));
      }
      if ((jsonObj.get("updated_at") != null && !jsonObj.get("updated_at").isJsonNull()) && !jsonObj.get("updated_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `updated_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updated_at").toString()));
      }
      if (!jsonObj.get("audience_segment_type").isJsonNull() && (jsonObj.get("audience_segment_type") != null && !jsonObj.get("audience_segment_type").isJsonNull()) && !jsonObj.get("audience_segment_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `audience_segment_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("audience_segment_type").toString()));
      }
      if ((jsonObj.get("tag_list") != null && !jsonObj.get("tag_list").isJsonNull()) && !jsonObj.get("tag_list").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tag_list` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tag_list").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("target_geolocations") != null && !jsonObj.get("target_geolocations").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `target_geolocations` to be an array in the JSON string but got `%s`", jsonObj.get("target_geolocations").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BillboardsGetByIdResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BillboardsGetByIdResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BillboardsGetByIdResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BillboardsGetByIdResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<BillboardsGetByIdResponse>() {
           @Override
           public void write(JsonWriter out, BillboardsGetByIdResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public BillboardsGetByIdResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             BillboardsGetByIdResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BillboardsGetByIdResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BillboardsGetByIdResponse
  * @throws IOException if the JSON string is invalid with respect to BillboardsGetByIdResponse
  */
  public static BillboardsGetByIdResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BillboardsGetByIdResponse.class);
  }

 /**
  * Convert an instance of BillboardsGetByIdResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

