/*
 * Forem API V1
 * Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.Comment;
import com.konfigthis.client.model.CommentsGetThreadedCommentResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CommentsApi
 */
@Disabled
public class CommentsApiTest {

    private static CommentsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new CommentsApi(apiClient);
    }

    /**
     * Comments
     *
     * This endpoint allows the client to retrieve all comments belonging to an article or podcast episode as threaded conversations.  It will return the all top level comments with their nested comments as threads. See the format specification for further details.  It supports pagination, each page will contain &#x60;50&#x60; top level comments (and as many child comments they have) by default.  If the page parameter is not passed, all comments of an article or podcast will be returned. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllThreadedTest() throws ApiException {
        Integer perPage = null;
        String aId = null;
        String pId = null;
        Integer page = null;
        List<Comment> response = api.getAllThreaded()
                .perPage(perPage)
                .aId(aId)
                .pId(pId)
                .page(page)
                .execute();
        // TODO: test validations
    }

    /**
     * Comment by id
     *
     * This endpoint allows the client to retrieve a comment as well as his descendants comments.    It will return the required comment (the root) with its nested descendants as a thread.    See the format specification for further details.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getThreadedCommentTest() throws ApiException {
        Integer id = null;
        CommentsGetThreadedCommentResponse response = api.getThreadedComment(id)
                .execute();
        // TODO: test validations
    }

}
